### ISSUE TITLE
ForkCMS 8.1 --> Blank screen

### ISSUE THREAD

**Issue by loosebruce** [guytarded/forkcms-links-module#4]
On ForkCMS 3.8.1 after installing the module manually.

I navigate to Modules --> Links and there is just a blank HTML page presented.
I will check the logs later.

**Comment by guytarded** [comment]
@loosebruce can you test if the code is working now?

**Comment by loosebruce** [comment]
Still the same problem with a blank screen, is there any place I can look to get more detailed log information?

**Comment by guytarded** [comment]
This module is now fully functional again. Thanks for creating the issue @loosebruce
