### ISSUE TITLE
Bad Traduction

### ISSUE THREAD

**Issue by alexisrosique** [guytarded/forkcms-links-module#7]
Hi! When I go to insert link in Submit Bottom put "Toevoegen" this is a bad translation.
Thanks you for links module it's great!

**Comment by guytarded** [comment]
Hi Alexis,

What do you suggest as a better translation?

**Comment by alexisrosique** [comment]
Hi, yes I want this, Thanks you.

**Comment by guytarded** [comment]
Finally found the issue, fixed.
